name: release

on:
  release:
    types:
      - created

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel
        pip install twine

    - name: Build Packages
      run: |
        python setup.py bdist_wheel
        python setup.py sdist

    - name: Check Distribution Files
      run: |
        twine check dist/*

    - name: Publish to PyPI
      run: |
        twine upload --verbose --disable-progress-bar dist/*

      env:
        TWINE_USERNAME: '__token__'
        TWINE_PASSWORD: ${{ secrets.pypi_token }}
